[package]
name = "clox-rust"
version = "0.1.0"
authors = ["norlen <joacim.norlen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
radix_trie = "0.2"
colored = "2.0.0"
